{"uid":"127a8d1d9da43818","name":"Checks host app card color is set to blue","fullName":"Checks host app card color is set to blue","historyId":"cc19420104f1273d88a6af49478344d8","time":{"start":1681666564326,"stop":1681666565649,"duration":1323},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at <unknown> (http://localhost:4173/src/bootstrap.tsx:5:10)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at <unknown> (http://localhost:4173/src/bootstrap.tsx:5:10)","steps":[{"name":"\"before each\" hook","time":{"start":1681666564326,"stop":1681666564553,"duration":227},"status":"passed","steps":[{"name":"visit http://localhost:4173","time":{"start":1681666564434,"stop":1681666564553,"duration":119},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"get [data-e2e=\"APP__CARD\"]","time":{"start":1681666564555,"stop":1681666565649,"duration":1094},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565648,"stop":1681666565648,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565649,"stop":1681666565649,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"[data-e2e=\"APP__CARD\"] request","time":{"start":1681666565649,"stop":1681666565649,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"uncaught exception TypeError: ReactDOM.createRoot is not a function","time":{"start":1681666565649,"stop":1681666565649,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"1cd370ea55c5af0","name":"e2e/tests/runAll.cy.ts:2023-04-16T17:36:05.293Z:attempt-1","source":"1cd370ea55c5af0.png","type":"image/png","size":153285},{"uid":"3da7591c4f6a0178","name":"video recording","source":"3da7591c4f6a0178.mp4","type":"video/mp4","size":3489871}],"parameters":[],"stepsCount":19,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.tests.runAll.cy.ts"},{"name":"parentSuite","value":"Vite React Microfrontends"},{"name":"suite","value":"It checks host app"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b54567474b358b1e","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681666563594,"stop":1681666564322,"duration":728}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":33,"broken":0,"skipped":0,"passed":111,"unknown":0,"total":144},"items":[{"uid":"4f339335a773bb60","reportUrl":"https://module-federation.github.io/module-federation-examples/710//#testresult/4f339335a773bb60","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681596532087,"stop":1681596533732,"duration":1645}},{"uid":"f42da23ff783ad83","reportUrl":"https://module-federation.github.io/module-federation-examples/707//#testresult/f42da23ff783ad83","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681537403392,"stop":1681537404899,"duration":1507}},{"uid":"6d1dff8763ee3a76","reportUrl":"https://module-federation.github.io/module-federation-examples/704//#testresult/6d1dff8763ee3a76","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681519374962,"stop":1681519376055,"duration":1093}},{"uid":"1bda1930801ddd17","reportUrl":"https://module-federation.github.io/module-federation-examples/696//#testresult/1bda1930801ddd17","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681338401135,"stop":1681338402577,"duration":1442}},{"uid":"ab77a5aa6a283a60","reportUrl":"https://module-federation.github.io/module-federation-examples/695//#testresult/ab77a5aa6a283a60","status":"passed","time":{"start":1681324157944,"stop":1681324158729,"duration":785}},{"uid":"b629ba69952d5be9","reportUrl":"https://module-federation.github.io/module-federation-examples/694//#testresult/b629ba69952d5be9","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681323457080,"stop":1681323458478,"duration":1398}},{"uid":"89b4b38877dc67a5","reportUrl":"https://module-federation.github.io/module-federation-examples/693//#testresult/89b4b38877dc67a5","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681299807869,"stop":1681299809507,"duration":1638}},{"uid":"1dae8176cccf1706","reportUrl":"https://module-federation.github.io/module-federation-examples/687//#testresult/1dae8176cccf1706","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681214573903,"stop":1681214575626,"duration":1723}},{"uid":"d41a2b3f9c8c3e11","reportUrl":"https://module-federation.github.io/module-federation-examples/686//#testresult/d41a2b3f9c8c3e11","status":"passed","time":{"start":1681146967021,"stop":1681146968045,"duration":1024}},{"uid":"a4a5f33a8f67f349","reportUrl":"https://module-federation.github.io/module-federation-examples/685//#testresult/a4a5f33a8f67f349","status":"passed","time":{"start":1681146967021,"stop":1681146968045,"duration":1024}},{"uid":"a530de364d5bfd89","reportUrl":"https://module-federation.github.io/module-federation-examples/684//#testresult/a530de364d5bfd89","status":"passed","time":{"start":1681136329990,"stop":1681136330893,"duration":903}},{"uid":"b1bce425aa597d8b","reportUrl":"https://module-federation.github.io/module-federation-examples/683//#testresult/b1bce425aa597d8b","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681099505263,"stop":1681099506528,"duration":1265}},{"uid":"d891aa831e23d0b0","reportUrl":"https://module-federation.github.io/module-federation-examples/682//#testresult/d891aa831e23d0b0","status":"passed","time":{"start":1681098138096,"stop":1681098138865,"duration":769}},{"uid":"53d2f8adeaa0ad01","reportUrl":"https://module-federation.github.io/module-federation-examples/671//#testresult/53d2f8adeaa0ad01","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1680987651525,"stop":1680987652653,"duration":1128}},{"uid":"377f1c5f85562c6","reportUrl":"https://module-federation.github.io/module-federation-examples/665//#testresult/377f1c5f85562c6","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1680909803449,"stop":1680909804566,"duration":1117}},{"uid":"df2ec647c8cd4130","reportUrl":"https://module-federation.github.io/module-federation-examples/661//#testresult/df2ec647c8cd4130","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1680834522800,"stop":1680834525047,"duration":2247}},{"uid":"224e694d3895971e","reportUrl":"https://module-federation.github.io/module-federation-examples/657//#testresult/224e694d3895971e","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1680806539817,"stop":1680806541257,"duration":1440}},{"uid":"96982465878cbe66","reportUrl":"https://module-federation.github.io/module-federation-examples/630//#testresult/96982465878cbe66","status":"passed","time":{"start":1680739143742,"stop":1680739144731,"duration":989}},{"uid":"f015633eca3a5a76","reportUrl":"https://module-federation.github.io/module-federation-examples/619//#testresult/f015633eca3a5a76","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1680701541786,"stop":1680701543602,"duration":1816}},{"uid":"b05284b48b0003b2","reportUrl":"https://module-federation.github.io/module-federation-examples/616//#testresult/b05284b48b0003b2","status":"passed","time":{"start":1680695670577,"stop":1680695671240,"duration":663}}]},"tags":[]},"source":"127a8d1d9da43818.json","parameterValues":[]}