{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Module build failed (from ./node_modules/ts-loader/index.js):\nError: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.\n    at Object.resolveTypeReferenceDirective (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:43500:18)\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:244:56\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:87:142\n    at Array.map (<anonymous>)\n    at Object.resolveTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:87:125)\n    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:119382:163)\n    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:119682:26)\n    at processTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:121185:31)\n    at findSourceFileWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:121070:21)\n    at findSourceFile (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:120922:26)\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App build and running & Check app elements exist","uid":"ae88951082e1ab61","parentUid":"7c0a94a463b85fcd5d1f4415ae037487","status":"failed","time":{"start":1680758505350,"stop":1680758505351,"duration":1},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check Main Tab Functionality","uid":"5b1a12cfd440e2b6","parentUid":"7c0a94a463b85fcd5d1f4415ae037487","status":"failed","time":{"start":1680758505352,"stop":1680758505352,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check UI Library elements","uid":"e0988667c659bc64","parentUid":"7c0a94a463b85fcd5d1f4415ae037487","status":"failed","time":{"start":1680758505352,"stop":1680758505352,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7c0a94a463b85fcd5d1f4415ae037487"},{"name":"The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > window.confirm wasn't called within 1s\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nBecause this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check is Comprehensive Demo...`","children":[{"name":"Check Dialog elements","uid":"621446b7dab25249","parentUid":"008a39cd97ac7fd5a612102abe00fb7c","status":"failed","time":{"start":1680758505352,"stop":1680758505352,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"008a39cd97ac7fd5a612102abe00fb7c"},{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Module build failed (from ./node_modules/ts-loader/index.js):\nError: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.\n    at Object.resolveTypeReferenceDirective (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:43500:18)\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:244:56\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:87:142\n    at Array.map (<anonymous>)\n    at Object.resolveTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:87:125)\n    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:119382:163)\n    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:119682:26)\n    at processTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:121185:31)\n    at findSourceFileWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:121070:21)\n    at findSourceFile (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:120922:26)\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App build and running & Check app elements exist","uid":"185ee5f1e96a3177","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570056,"stop":1680758570064,"duration":8},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check Main Tab Functionality","uid":"2567bec4784b26d9","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570064,"stop":1680758570067,"duration":3},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check Dialog elements","uid":"edbc31bd01e88cf1","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570067,"stop":1680758570068,"duration":1},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check UI Library elements","uid":"1baed3577624be3d","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570067,"stop":1680758570067,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check Routing elements","uid":"e499d44cc588af0a","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570068,"stop":1680758570068,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"Check Svelte Page elements","uid":"8a3a034f24dc2f5f","parentUid":"683ff620e4fefa83ba39b6b84c0e074d","status":"failed","time":{"start":1680758570068,"stop":1680758570068,"duration":0},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"683ff620e4fefa83ba39b6b84c0e074d"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"The following error originated from your application code, not from Cypress.\n\n  > Module build failed (from ./node_modules/ts-loader/index.js):\nError: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.\n    at Object.resolveTypeReferenceDirective (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:43500:18)\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:244:56\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:87:142\n    at Array.map (<anonymous>)\n    at Object.resolveTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/ts-loader/dist/servicesHost.js:87:125)\n    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:119382:163)\n    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:119682:26)\n    at processTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:121185:31)\n    at findSourceFileWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:121070:21)\n    at findSourceFile (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react16/app-05/node_modules/typescript/lib/typescript.js:120922:26)\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App build and running & Check app elements exist","uid":"8942b664a34649bd","parentUid":"95021f424e4c351fe208a7e4a6ab5d0a","status":"broken","time":{"start":1680758505934,"stop":1680758506293,"duration":359},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"95021f424e4c351fe208a7e4a6ab5d0a"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Module build failed (from ./node_modules/ts-loader/index.js):\nError: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.\n    at Object.resolveTypeReferenceDirective (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:43500:18)\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:244:56\n    at /home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:87:142\n    at Array.map (<anonymous>)\n    at Object.resolveTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/ts-loader/dist/servicesHost.js:87:125)\n    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:119382:163)\n    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:119682:26)\n    at processTypeReferenceDirectives (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:121185:31)\n    at findSourceFileWorker (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:121070:21)\n    at findSourceFile (/home/runner/work/module-federation-examples/module-federation-examples/comprehensive-demo-react18/app-05/node_modules/typescript/lib/typescript.js:120922:26)\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App build and running & Check app elements exist","uid":"c9353b9bf59e024b","parentUid":"0f50fdd4cb379083c974d4c8bf33ed41","status":"broken","time":{"start":1680758570796,"stop":1680758571297,"duration":501},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0f50fdd4cb379083c974d4c8bf33ed41"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}